### ISSUE TITLE
Activity for adding a stolen car

### ISSUE THREAD

**Issue by vasekstebra** [VaclavStebra/stolen-car-database#3]
https://material.io/guidelines/components/buttons-floating-action-button.html on main activity?

**Comment by rduriancik** [comment]
I'm thinking about using your detail fragment as the last step in the car adding process as a summary.

**Comment by vasekstebra** [comment]
Can be - You can show the fragment once the car is added.

**Comment by rduriancik** [comment]
1. step - Basic info + optional info
2. step - Photo
3. step - Location
4. step - Summary

**Comment by vasekstebra** [comment]
Sounds good.

I will try to finish my currently assigned tasks by the end of this week
so you can use it.
