### ISSUE TITLE
Display map with all stolen cars locations

### ISSUE THREAD

**Issue by vasekstebra** [VaclavStebra/stolen-car-database#6]

**Comment by vasekstebra** [comment]
@rduriancik - Thinking about this, I think we can instead display the map inside the detail fragment for the given car. It will be more clear for the users to also view it's location directly on the map and not only coordinates. What do you think?

**Comment by rduriancik** [comment]
Yes, it would be better. But if we want to display all stolen cars on the map at once we also need to implement some fragment for that.

**Comment by vasekstebra** [comment]
I agree

**Comment by rduriancik** [comment]
https://developers.google.com/maps/documentation/android-api/lite
